name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-gnutls-dev libhts-dev libboost-date-time-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libboost-iostreams-dev
      - uses: jtdor/build-deb-action@v1
        id: build-deb
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          host-arch: arm64
          package_root: .debpkg
      - name: Upload deb to release
        uses: softprops/action-gh-release@v1
        if: steps.build-deb.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build-deb.outputs.release_tag }}
          body: 'Release ${{ steps.build-deb.outputs.release_tag }}'
          files: .debpkg/*.deb
          prerelease: true
