name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-gnutls-dev libhts-dev libboost-date-time-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libboost-iostreams-dev
      - uses: jiro4989/build-deb-action@v2
        id: build-deb
        with:
          package: tracy
          package_root: .debpkg
          maintainer: your_name
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'arm64'
          depends: 'libc6 (>= 2.2.1), libcurl4-gnutls, libhts-dev, libboost-date-time-dev, libboost-program-options-dev, libboost-system-dev, libboost-filesystem-dev, libboost-iostreams-dev'
          desc: 'this is sample package.'
      - name: Upload deb to release
        uses: softprops/action-gh-release@v1
        if: steps.build-deb.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build-deb.outputs.release_tag }}
          body: 'Release ${{ steps.build-deb.outputs.release_tag }}'
          files: .debpkg/*.deb
          prerelease: true
